name: Deploy HTML to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Node (opcional, se não usa build com Node, remova)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Deploy to gh-pages
        run: |
          mkdir ../gh-pages
          cp -r * ../gh-pages/
          cd ../gh-pages

          touch .nojekyll  # permite arquivos com underscore
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy automatic to GitHub Pages"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push --force origin gh-pages

